image: "thlmylab/swakkd:stable"

variables:
  PRIME: "yes"
  CACHE: "persistent"  # Simplified to always use persistent cache

stages:
  - prepare
  - build
  - deploy

prepare:
  stage: prepare
  script:
    - kubectl delete secret gitlab-registry-credentials || true
    - kubectl create secret docker-registry gitlab-registry-credentials \
        --docker-server=$CI_REGISTRY \
        --docker-username=image-registry \
        --docker-password=$CI_REGISTRY_TOKEN

build-prime:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - cd prime
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/prime:latest .
    - docker push $CI_REGISTRY_IMAGE/prime:latest

deploy:
  stage: deploy
  script:
    # Deploy Prime Service and Redis Cache
    - kubectl apply -f deploy/prime/prime.yaml  # Combined YAML file for prime service
    - kubectl apply -f deploy/persistent-redis.yaml
    - kubectl apply -f deploy/storage.yaml
